[bot]
# Token del bot de Discord (obtén uno en https://discord.com/developers/applications)
token = "tu_token_aqui"

# Prefijo para comandos
prefix = "!"

[logging]
# Nivel de logging (debug, info, warn, error)
level = "info"

# Habilitar logs detallados
detailed = true 